-- CREAMOS LA BASE DE DATOS
CREATE DATABASE VIDEOJUEGOS; 
USE VIDEOJUEGOS;

-- CREAMOS LAS TABLAS
create table JUEGOS(
CODETAPA int(3) not null primary key,
NOMBREJUGADOR varchar(15),
PUNTAJE int(6)
)engine=innodb;

create table MASTER(
NUMETAPA int(3) not null primary key,
NOMJUGADOR varchar(15),
PUNTOSJUGADOR int(6)
)engine=innodb;

-- INSERTAMOS LOS 8 REGISTROS
INSERT INTO JUEGOS VALUES(1,'JUAN1',10);
INSERT INTO JUEGOS VALUES(2,'JUAN2',20);
INSERT INTO JUEGOS VALUES(3,'JUAN3',30);
INSERT INTO JUEGOS VALUES(4,'JUAN4',40);
INSERT INTO JUEGOS VALUES(5,'JUAN5',50);
INSERT INTO JUEGOS VALUES(6,'JUAN6',60);
INSERT INTO JUEGOS VALUES(7,'JUAN7',70);
INSERT INTO JUEGOS VALUES(8,'JUAN8',80);